# Generated by Django 6.0.1 on 2026-01-30 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_num', models.CharField(max_length=4)),
                ('room_type', models.CharField(max_length=50)),
                ('room_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('room_image', models.ImageField(upload_to='rooms/')),
                ('room_service', models.CharField(max_length=100)),
                ('room_capacity', models.CharField(max_length=10)),
                ('room_description', models.CharField(max_length=200)),
                ('room_available', models.BooleanField(default=True)),
                ('room_rating', models.FloatField(default=0)),
            ],
        ),
    ]
